# -*- coding: utf-8 -*-
"""Major Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1smE7hJSoyu93wqlOYAiY340tcg5skg1I
"""

!pip install streamlit --quiet
!pip install pyngrok==4.1.1 --quiet
from pyngrok import ngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st 
# import os
# from textblob import TextBlob 
# 
# # Title
# st.title("Sentiment Analysis")
# 
# result_sentiment = 2
# # Sentiment Analysis
# st.subheader("Analyse Your Text")
# 
# message = st.text_area("Enter Text")
# if st.button("Analyze"):
# 			blob = TextBlob(message)
# 			result_sentiment = blob.sentiment[0]
# 			
#     
# if result_sentiment > 0.5 and result_sentiment < 1 :
#       st.write('Prediction  :')
#       st.subheader('Positive')
#       st.success(f'Score : {result_sentiment}')
# 
# elif result_sentiment < 0 :
#       st.write('Prediction  :')
#       st.subheader('Negative')
#       st.success(f'Score : {result_sentiment}')
# 
# elif result_sentiment > 0 or result_sentiment <= 0.5 :
#       st.write('Prediction  :')
#       st.subheader('Neutral')
#       st.success(f'Score : {result_sentiment}')
#

!nohup streamlit run app.py &

url = ngrok.connect(port='8501')
url